
# This file is part of the dinListPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# Plugin schema file for Doctrine
#
# @package     dinListPlugin
# @subpackage  config.doctrine
# @author      Nicolay N. Zyk <relo.san@gmail.com>

#DinList
DinList:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        model:              { type: 'string(150)', fixed: true, notnull: true }
        name:               { type: 'string(150)', fixed: true, notnull: true }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        is_editable:        { type: 'boolean', notnull: true, default: true }
        key_type:           { type: 'integer(1)', notnull: true, default: '1' }
        title:              { type: 'string(150)', fixed: true }
        description:        { type: 'clob(65532)' }
        sequence:           { type: 'integer(4)' }

    indexes:
        enabled:            { fields: ['is_enabled'] }
        list:               { fields: ['model', 'name'], type: 'unique' }


#DinListField
DinListField:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        list_id:            { type: 'integer(4)', notnull: true }
        name:               { type: 'string(150)', fixed: true, notnull: true }
        type:               { type: 'integer(1)', notnull: true, default: '1' }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        is_i18n:            { type: 'boolean', notnull: true, default: true }
        is_editable:        { type: 'boolean', notnull: true, default: true }
        is_listable:        { type: 'boolean', notnull: true, default: false }
        title:              { type: 'string(150)', fixed: true }
        description:        { type: 'clob(65532)' }

    indexes:
        enabled:            { fields: ['list_id', 'is_enabled'] }
        list:               { fields: ['list_id', 'name'], type: 'unique' }

    relations:
        DinList:
            local:          'list_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'List'
            foreignAlias:   'Fields'
            onDelete:       'CASCADE'


#DinListPair
DinListPair:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        list_id:            { type: 'integer(4)', notnull: true }
        keyword:            { type: 'string(150)', fixed: true, notnull: true }
        is_enabled:         { type: 'boolean', notnull: true, default: true }
        is_public:          { type: 'boolean', notnull: true, default: true }
        is_editable:        { type: 'boolean', notnull: true, default: true }
        title:              { type: 'string(250)', fixed: true }
        description:        { type: 'clob(65532)' }
        sequence:           { type: 'integer(4)' }

    indexes:
        enabled:            { fields: ['list_id', 'is_enabled'] }
        item:               { fields: ['list_id', 'keyword'], type: 'unique' }

    relations:
        DinList:
            local:          'list_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'List'
            foreignAlias:   'Pairs'
            onDelete:       'CASCADE'


#DinListPairParam
DinListPairParam:

    actAs:
        I18n:
            fields:         ['trans_value']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        pair_id:            { type: 'integer(4)', notnull: true }
        field_id:           { type: 'integer(4)', notnull: true }
        is_editable:        { type: 'boolean', notnull: true, default: true }
        value:              { type: 'clob' }
        trans_value:        { type: 'clob' }

    indexes:
        param:              { fields: ['pair_id', 'field_id'], type: 'unique' }

    relations:
        DinListPair:
            local:          'pair_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'Pair'
            foreignAlias:   'Params'
            onDelete:       'CASCADE'
        DinListField:
            local:          'field_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'Field'
            foreignAlias:   'Params'
            onDelete:       'CASCADE'

#EOF